"""add_user_preferences_table

Revision ID: 12c57b79eb64
Revises: 1e84a29b4b4d
Create Date: 2026-04-26 01:05:18.001659

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '12c57b79eb64'
down_revision: Union[str, None] = '1e84a29b4b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('show_empty_courses', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###

    # Migrate existing users: create default preference record for each user
    op.execute(
        """
        INSERT INTO user_preferences (id, user_id, show_empty_courses, create_time, updated_time)
        SELECT UUID(), id, 1, NOW(), NOW() FROM users
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
