"""db migration, departments

Revision ID: 15c70c3a65d3
Revises: af84e9f4a63c
Create Date: 2023-12-15 00:24:01.417140

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15c70c3a65d3"
down_revision: Union[str, None] = "af84e9f4a63c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_departments",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=True),
        sa.Column("department_id", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_departments")
    # ### end Alembic commands ###
