"""db migration, mutiple files

Revision ID: 204127fb3744
Revises: 9ab4552f4171
Create Date: 2023-11-28 12:42:59.548530

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "204127fb3744"
down_revision: Union[str, None] = "9ab4552f4171"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
