"""add_default_is_anonymous

Revision ID: 2555095e0ae9
Revises: c0856f5ce590
Create Date: 2026-04-30 08:00:09.987407

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2555095e0ae9'
down_revision: Union[str, None] = 'c0856f5ce590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('default_is_anonymous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
