"""db migration, post

Revision ID: 26d05dc9a63d
Revises: 3e0d6835822e
Create Date: 2023-11-29 20:09:00.725637

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26d05dc9a63d"
down_revision: Union[str, None] = "3e0d6835822e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_description", table_name="posts")
    op.drop_index("ix_posts_title", table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_posts_files_description", table_name="posts_files")
    op.drop_index("ix_posts_files_title", table_name="posts_files")
    op.drop_table("posts_files")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts_files",
        sa.Column("id", mysql.VARCHAR(length=256), nullable=False),
        sa.Column("title", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("description", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("owner_id", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("group_id", mysql.VARCHAR(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_posts_files_title", "posts_files", ["title"], unique=False)
    op.create_index(
        "ix_posts_files_description",
        "posts_files",
        ["description"],
        unique=False,
    )
    op.create_table(
        "posts",
        sa.Column("id", mysql.VARCHAR(length=256), nullable=False),
        sa.Column("title", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("description", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("owner_id", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("group_id", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("course_id", mysql.VARCHAR(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_posts_title", "posts", ["title"], unique=False)
    op.create_index("ix_posts_description", "posts", ["description"], unique=False)
    # ### end Alembic commands ###
