"""db migration, school  department

Revision ID: 4da81afb7b6c
Revises: 7577872e42b4
Create Date: 2023-12-18 23:33:57.681356

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4da81afb7b6c"
down_revision: Union[str, None] = "7577872e42b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("school_department", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "school_department")
    # ### end Alembic commands ###
