"""db migration, add related with department

Revision ID: 56947cc2d6e0
Revises: ffb25847e6ca
Create Date: 2023-12-16 00:10:23.241456

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56947cc2d6e0"
down_revision: Union[str, None] = "ffb25847e6ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bulletins", sa.Column("department_id", sa.String(length=256), nullable=True)
    )
    op.create_index(
        op.f("ix_bulletins_department_id"), "bulletins", ["department_id"], unique=False
    )
    op.add_column(
        "posts", sa.Column("department_id", sa.String(length=256), nullable=True)
    )
    op.create_index(
        op.f("ix_posts_department_id"), "posts", ["department_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_department_id"), table_name="posts")
    op.drop_column("posts", "department_id")
    op.drop_index(op.f("ix_bulletins_department_id"), table_name="bulletins")
    op.drop_column("bulletins", "department_id")
    # ### end Alembic commands ###
