"""db migration, request status default pending

Revision ID: 65aab4d0944f
Revises: 79eb4c2e02f3
Create Date: 2023-12-15 00:48:14.545145

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65aab4d0944f"
down_revision: Union[str, None] = "79eb4c2e02f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_departments", "status", server_default="PENDING")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
