"""db migration, user id

Revision ID: 65c84c08c11f
Revises: 6938c4e11d73
Create Date: 2023-12-06 11:52:08.859526

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65c84c08c11f"
down_revision: Union[str, None] = "6938c4e11d73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY (id);")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP CONSTRAINT users_pk;")
    pass
    # ### end Alembic commands ###
