"""db migration, use uui das id

Revision ID: 6e02a84a57e2
Revises: 41c05f3eb95f
Create Date: 2023-11-28 02:42:11.153620

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e02a84a57e2"
down_revision: Union[str, None] = "41c05f3eb95f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop FK on threads.owner_id -> users.id if it exists (can block dropping users.id)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "threads" in inspector.get_table_names():
        fks = inspector.get_foreign_keys("threads")
        for fk in fks:
            if fk.get("referred_table") == "users":
                op.drop_constraint(fk["name"], "threads", type_="foreignkey")

    # If tables were already created by metadata.create_all() with the final
    # schema (id as String), these intermediate migration steps are unnecessary.
    items_cols = {c["name"] for c in inspector.get_columns("items")}
    users_cols = {c["name"] for c in inspector.get_columns("users")}

    if "uuid" not in items_cols and "id" in items_cols:
        op.add_column(
            "items",
            sa.Column("uuid", sa.String(length=256), nullable=False),
        )
        op.alter_column(
            "items",
            "owner_id",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=256),
            existing_nullable=True,
        )
        op.drop_index("ix_items_id", table_name="items")
        op.drop_column("items", "id")

    if "uuid" not in users_cols and "id" in users_cols:
        op.add_column(
            "users",
            sa.Column("uuid", sa.String(length=256), nullable=False),
        )
        op.drop_index("ix_users_id", table_name="users")
        op.drop_column("users", "id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.drop_column("users", "uuid")
    op.add_column(
        "items",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_index("ix_items_id", "items", ["id"], unique=False)
    op.alter_column(
        "items",
        "owner_id",
        existing_type=sa.String(length=256),
        type_=mysql.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("items", "uuid")
    # ### end Alembic commands ###
