"""db migration, add index to user department

Revision ID: 7577872e42b4
Revises: 02a39342a98c
Create Date: 2023-12-16 16:38:15.943152

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7577872e42b4"
down_revision: Union[str, None] = "02a39342a98c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_users_departments_is_department_admin"),
        "users_departments",
        ["is_department_admin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_departments_status"),
        "users_departments",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_departments_status"), table_name="users_departments")
    op.drop_index(
        op.f("ix_users_departments_is_department_admin"), table_name="users_departments"
    )
    # ### end Alembic commands ###
