"""db migration, departments_courses

Revision ID: 79eb4c2e02f3
Revises: e7bae20f6ba2
Create Date: 2023-12-15 00:29:31.565985

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79eb4c2e02f3"
down_revision: Union[str, None] = "e7bae20f6ba2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "courses" not in tables:
        op.create_table(
            "courses",
            sa.Column("id", sa.String(length=256), nullable=False),
            sa.Column("name", sa.String(length=256), nullable=True),
            sa.Column("category", sa.String(length=256), nullable=True),
            sa.Column("department_id", sa.String(length=256), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_courses_department_id"), "courses", ["department_id"], unique=False
        )
    else:
        existing_indexes = {idx["name"] for idx in inspector.get_indexes("courses")}
        op.add_column(
            "courses", sa.Column("department_id", sa.String(length=256), nullable=True)
        )
        if "ix_courses_category" in existing_indexes:
            op.drop_index("ix_courses_category", table_name="courses")
        if "ix_courses_name" in existing_indexes:
            op.drop_index("ix_courses_name", table_name="courses")
        op.create_index(
            op.f("ix_courses_department_id"), "courses", ["department_id"], unique=False
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_department_id"), table_name="courses")
    op.create_index("ix_courses_name", "courses", ["name"], unique=False)
    op.create_index("ix_courses_category", "courses", ["category"], unique=False)
    op.drop_column("courses", "department_id")
    # ### end Alembic commands ###
