"""db migration, post status

Revision ID: 8b3d90cd8859
Revises: b6487b186c3e
Create Date: 2023-12-05 14:24:53.231196

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b3d90cd8859"
down_revision: Union[str, None] = "b6487b186c3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("status", sa.String(length=256), nullable=True))
    op.create_index(op.f("ix_posts_status"), "posts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_status"), table_name="posts")
    op.drop_column("posts", "status")
    # ### end Alembic commands ###
