"""db migration, password

Revision ID: 9412f4be82f5
Revises: 204127fb3744
Create Date: 2023-11-29 10:42:48.167936

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9412f4be82f5"
down_revision: Union[str, None] = "204127fb3744"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###
