"""extract comon column

Revision ID: 97bcd0f7d92c
Revises: cfeaac9eed4a
Create Date: 2024-01-04 01:13:37.834479

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97bcd0f7d92c"
down_revision: Union[str, None] = "cfeaac9eed4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bulletins",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "bulletins",
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "courses",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "courses", sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "departments",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "departments",
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_departments_is_public"), "departments", ["is_public"], unique=False
    )
    op.add_column(
        "posts",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "posts", sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "posts_files",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "posts_files",
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "users", sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users_departments",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "users_departments",
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_departments", "updated_time")
    op.drop_column("users_departments", "create_time")
    op.drop_column("users", "updated_time")
    op.drop_column("users", "create_time")
    op.drop_column("posts_files", "updated_time")
    op.drop_column("posts_files", "create_time")
    op.drop_column("posts", "updated_time")
    op.drop_column("posts", "create_time")
    op.drop_index(op.f("ix_departments_is_public"), table_name="departments")
    op.drop_column("departments", "updated_time")
    op.drop_column("departments", "create_time")
    op.drop_column("courses", "updated_time")
    op.drop_column("courses", "create_time")
    op.drop_column("bulletins", "updated_time")
    op.drop_column("bulletins", "create_time")
    # ### end Alembic commands ###
