"""db migration, use uuidas id

Revision ID: 9ab4552f4171
Revises: e7fccc22b25c
Create Date: 2023-11-28 12:35:18.854432

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ab4552f4171"
down_revision: Union[str, None] = "e7fccc22b25c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
