"""db migration, course

Revision ID: b6487b186c3e
Revises: 509a35d8aa05
Create Date: 2023-12-02 17:14:50.595178

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6487b186c3e"
down_revision: Union[str, None] = "509a35d8aa05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_items_description", table_name="items")
    op.drop_index("ix_items_title", table_name="items")
    op.drop_table("items")
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.create_table(
        "items",
        sa.Column("title", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("description", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("owner_id", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=256), nullable=False),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_items_title", "items", ["title"], unique=False)
    op.create_index("ix_items_description", "items", ["description"], unique=False)
    # ### end Alembic commands ###
