"""add_fk_to_user_preferences_and_user_departments

Revision ID: c0856f5ce590
Revises: 12c57b79eb64
Create Date: 2026-04-26 02:20:33.895194

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c0856f5ce590"
down_revision: Union[str, None] = "12c57b79eb64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clean up orphan records before adding FK constraints
    op.execute(
        """
        DELETE FROM users_departments
        WHERE user_id NOT IN (SELECT id FROM users)
           OR department_id NOT IN (SELECT id FROM departments)
        """
    )
    op.execute(
        """
        DELETE FROM user_preferences
        WHERE user_id NOT IN (SELECT id FROM users)
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_preferences", "user_id",
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column("user_preferences", "show_empty_courses",
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key("fk_user_preferences_user_id", "user_preferences", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_users_departments_user_id", "users_departments", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_users_departments_department_id", "users_departments", "departments", ["department_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_departments_department_id", "users_departments", type_="foreignkey")
    op.drop_constraint("fk_users_departments_user_id", "users_departments", type_="foreignkey")
    op.drop_constraint("fk_user_preferences_user_id", "user_preferences", type_="foreignkey")
    op.alter_column("user_preferences", "show_empty_courses",
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column("user_preferences", "user_id",
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
