"""post add is_anonymous column

Revision ID: de2df7639c82
Revises: 97bcd0f7d92c
Create Date: 2024-03-04 19:50:43.927407

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'de2df7639c82'
down_revision: Union[str, None] = '97bcd0f7d92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_anonymous')
    # ### end Alembic commands ###
