"""db migration

Revision ID: e18b34bf193b
Revises:
Create Date: 2023-11-28 02:24:06.100736

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e18b34bf193b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "users" not in tables:
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("email", sa.String(length=256), nullable=True),
            sa.Column("hashed_password", sa.String(length=256), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_users_id", "users", ["id"], unique=False)
        op.create_index("ix_users_email", "users", ["email"], unique=True)
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column(
            "users",
            "email",
            existing_type=mysql.TEXT(),
            type_=sa.String(length=256),
            existing_nullable=True,
        )
        op.alter_column(
            "users",
            "hashed_password",
            existing_type=mysql.TEXT(),
            type_=sa.String(length=256),
            existing_nullable=True,
        )
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
        op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
        # ### end Alembic commands ###

    if "items" not in tables:
        op.create_table(
            "items",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("title", sa.String(length=256), nullable=True),
            sa.Column("description", sa.String(length=256), nullable=True),
            sa.Column("owner_id", sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_items_id", "items", ["id"], unique=False)
        op.create_index("ix_items_title", "items", ["title"], unique=False)
        op.create_index("ix_items_description", "items", ["description"], unique=False)
