"""db migration

Revision ID: e18b34bf193b
Revises: 
Create Date: 2023-11-28 02:24:06.100736

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e18b34bf193b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=256),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=256),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=256),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
