"""db migration, use uuidas id

Revision ID: e7fccc22b25c
Revises: 6e02a84a57e2
Create Date: 2023-11-28 02:42:58.920542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7fccc22b25c"
down_revision: Union[str, None] = "6e02a84a57e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("id", sa.String(length=256), nullable=False))
    op.drop_column("items", "uuid")
    op.add_column("users", sa.Column("id", sa.String(length=256), nullable=False))
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("uuid", mysql.VARCHAR(length=256), nullable=False),
    )
    op.drop_column("users", "id")
    op.add_column(
        "items",
        sa.Column("uuid", mysql.VARCHAR(length=256), nullable=False),
    )
    op.drop_column("items", "id")
    # ### end Alembic commands ###
