"""db migration, use uuidas id

Revision ID: e7fccc22b25c
Revises: 6e02a84a57e2
Create Date: 2023-11-28 02:42:58.920542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7fccc22b25c"
down_revision: Union[str, None] = "6e02a84a57e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    table_names = set(inspector.get_table_names())

    def migrate_uuid_to_id(table_name: str) -> None:
        if table_name not in table_names:
            return

        cols = {c["name"] for c in inspector.get_columns(table_name)}
        has_uuid = "uuid" in cols
        has_id = "id" in cols

        if not has_uuid:
            return

        if not has_id:
            op.add_column(table_name, sa.Column("id", sa.String(length=256), nullable=True))
            op.execute(sa.text(f"UPDATE {table_name} SET id = uuid WHERE id IS NULL"))
            op.alter_column(table_name, "id", existing_type=sa.String(length=256), nullable=False)

        op.drop_column(table_name, "uuid")

    migrate_uuid_to_id("items")
    migrate_uuid_to_id("users")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("uuid", mysql.VARCHAR(length=256), nullable=False),
    )
    op.drop_column("users", "id")
    op.add_column(
        "items",
        sa.Column("uuid", mysql.VARCHAR(length=256), nullable=False),
    )
    op.drop_column("items", "id")
    # ### end Alembic commands ###
