"""db migration, user is department admin

Revision ID: ffb25847e6ca
Revises: 65aab4d0944f
Create Date: 2023-12-15 20:46:50.114141

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffb25847e6ca"
down_revision: Union[str, None] = "65aab4d0944f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_departments", sa.Column("is_admin", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_departments", "is_admin")
    # ### end Alembic commands ###
